name: msn
description: A new Flutter project

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.18.1
  image_picker: ^0.8.5
  file_picker: ^4.2.0
  video_player: ^2.2.10 
  image_gallery_saver: ^1.7.1
  http: ^0.13.3
  permission_handler: ^10.0.1
  vibration: ^1.7.3
  provider: ^5.0.0
  sqflite: ^2.0.0+4
  path_provider: ^2.0.8
  url_launcher: ^6.0.0
  shared_preferences: ^2.0.8
  flutter_localizations:
    sdk: flutter
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - img/
